require("dotenv").config({ path: "./config.env" });
export const {
    LOG_STORAGE_STRATEGY,
    PORT,
    DB_URL,
    DEBUG_MODE,
    JWT_SECRET,
    JWT_EXPIRE,
    COOKIE_EXPIRE,
    FRONTEND_URL,
    AWS_CLIENT_ID,
    AWS_CLIENT_SECRET,
    AWS_REGION,
    AWS_BUCKET_NAME,
    SMTP_MAIL,
    SMTP_SERVICE,
    SMTP_HOST,
    SMTP_PORT,
    SMTP_PASS,
    IS_S3,
    CLOUDINARY_NAME,
    CLOUDINARY_API_KEY,
    CLOUDINARY_API_SECRET,
    RATE_LIMIT_WINDOW_MS,
    RATE_LIMIT_MAX,
} = process.env;
